// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="winning_winning,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=229,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=506,HLS_SYN_LUT=1742,HLS_VERSION=2023_1}" *)

module winning (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        board_Addr_A,
        board_EN_A,
        board_WEN_A,
        board_Din_A,
        board_Dout_A,
        board_Clk_A,
        board_Rst_A,
        result
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] board_Addr_A;
output   board_EN_A;
output  [0:0] board_WEN_A;
output  [7:0] board_Din_A;
input  [7:0] board_Dout_A;
output   board_Clk_A;
output   board_Rst_A;
output  [31:0] result;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] board_Addr_A;
reg board_EN_A;
reg[31:0] result;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_return;
reg   [0:0] targetBlock_reg_201;
wire    ap_CS_fsm_state2;
wire   [0:0] grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_return;
reg   [0:0] targetBlock1_reg_205;
wire    ap_CS_fsm_state4;
wire   [0:0] grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_return;
reg   [0:0] targetBlock2_reg_209;
wire    ap_CS_fsm_state6;
wire   [0:0] grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_return;
reg   [0:0] targetBlock3_reg_213;
wire    ap_CS_fsm_state8;
wire    grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start;
wire    grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_done;
wire    grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_idle;
wire    grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_ready;
wire   [31:0] grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_Addr_A;
wire    grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_EN_A;
wire   [0:0] grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_WEN_A;
wire   [7:0] grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_Din_A;
wire   [7:0] grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_symbol_out;
wire    grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_symbol_out_ap_vld;
wire    grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start;
wire    grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_done;
wire    grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_idle;
wire    grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_ready;
wire   [31:0] grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_Addr_A;
wire    grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_EN_A;
wire   [0:0] grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_WEN_A;
wire   [7:0] grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_Din_A;
wire   [7:0] grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_symbol_1_out;
wire    grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_symbol_1_out_ap_vld;
wire    grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start;
wire    grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_done;
wire    grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_idle;
wire    grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_ready;
wire   [31:0] grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_Addr_A;
wire    grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_EN_A;
wire   [0:0] grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_WEN_A;
wire   [7:0] grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_Din_A;
wire   [7:0] grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_symbol_2_out;
wire    grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_symbol_2_out_ap_vld;
wire    grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start;
wire    grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_done;
wire    grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_idle;
wire    grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_ready;
wire   [31:0] grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_Addr_A;
wire    grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_EN_A;
wire   [0:0] grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_WEN_A;
wire   [7:0] grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_Din_A;
wire   [7:0] grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_symbol_3_out;
wire    grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_symbol_3_out_ap_vld;
wire    grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start;
wire    grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_done;
wire    grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_idle;
wire    grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_ready;
wire   [31:0] grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_Addr_A;
wire    grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_EN_A;
wire   [0:0] grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_WEN_A;
wire   [7:0] grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_Din_A;
wire   [0:0] grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_return;
reg    grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start_reg;
reg   [7:0] symbol_loc_fu_58;
reg    grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [7:0] symbol_1_loc_fu_54;
reg    grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [7:0] symbol_2_loc_fu_50;
reg    grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start_reg;
wire    ap_CS_fsm_state7;
reg   [7:0] symbol_3_loc_fu_46;
reg    grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire   [31:0] select_ln22_fu_114_p3;
reg   [31:0] result_preg;
wire   [31:0] select_ln38_fu_132_p3;
wire   [31:0] select_ln54_fu_150_p3;
wire   [31:0] select_ln70_fu_168_p3;
reg    ap_predicate_op54_call_state10;
reg    ap_block_state10_on_subcall_done;
wire   [0:0] icmp_ln22_fu_108_p2;
wire   [0:0] icmp_ln38_fu_126_p2;
wire   [0:0] icmp_ln54_fu_144_p2;
wire   [0:0] icmp_ln70_fu_162_p2;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start_reg = 1'b0;
#0 grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start_reg = 1'b0;
#0 grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start_reg = 1'b0;
#0 grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start_reg = 1'b0;
#0 grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start_reg = 1'b0;
#0 result_preg = 32'd0;
end

winning_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2 grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start),
    .ap_done(grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_done),
    .ap_idle(grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_idle),
    .ap_ready(grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_ready),
    .board_Addr_A(grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_Addr_A),
    .board_EN_A(grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_EN_A),
    .board_WEN_A(grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_WEN_A),
    .board_Din_A(grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_Din_A),
    .board_Dout_A(board_Dout_A),
    .symbol_out(grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_symbol_out),
    .symbol_out_ap_vld(grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_symbol_out_ap_vld),
    .ap_return(grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_return)
);

winning_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4 grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start),
    .ap_done(grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_done),
    .ap_idle(grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_idle),
    .ap_ready(grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_ready),
    .board_Addr_A(grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_Addr_A),
    .board_EN_A(grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_EN_A),
    .board_WEN_A(grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_WEN_A),
    .board_Din_A(grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_Din_A),
    .board_Dout_A(board_Dout_A),
    .symbol_1_out(grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_symbol_1_out),
    .symbol_1_out_ap_vld(grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_symbol_1_out_ap_vld),
    .ap_return(grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_return)
);

winning_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6 grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start),
    .ap_done(grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_done),
    .ap_idle(grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_idle),
    .ap_ready(grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_ready),
    .board_Addr_A(grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_Addr_A),
    .board_EN_A(grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_EN_A),
    .board_WEN_A(grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_WEN_A),
    .board_Din_A(grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_Din_A),
    .board_Dout_A(board_Dout_A),
    .symbol_2_out(grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_symbol_2_out),
    .symbol_2_out_ap_vld(grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_symbol_2_out_ap_vld),
    .ap_return(grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_return)
);

winning_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8 grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start),
    .ap_done(grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_done),
    .ap_idle(grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_idle),
    .ap_ready(grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_ready),
    .board_Addr_A(grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_Addr_A),
    .board_EN_A(grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_EN_A),
    .board_WEN_A(grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_WEN_A),
    .board_Din_A(grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_Din_A),
    .board_Dout_A(board_Dout_A),
    .symbol_3_out(grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_symbol_3_out),
    .symbol_3_out_ap_vld(grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_symbol_3_out_ap_vld),
    .ap_return(grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_return)
);

winning_winning_Pipeline_VITIS_LOOP_77_9 grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start),
    .ap_done(grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_done),
    .ap_idle(grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_idle),
    .ap_ready(grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_ready),
    .board_Addr_A(grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_Addr_A),
    .board_EN_A(grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_EN_A),
    .board_WEN_A(grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_WEN_A),
    .board_Din_A(grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_Din_A),
    .board_Dout_A(board_Dout_A),
    .ap_return(grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start_reg <= 1'b1;
        end else if ((grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_ready == 1'b1)) begin
            grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start_reg <= 1'b0;
    end else begin
        if (((targetBlock_reg_201 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start_reg <= 1'b1;
        end else if ((grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_ready == 1'b1)) begin
            grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start_reg <= 1'b0;
    end else begin
        if (((targetBlock1_reg_205 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start_reg <= 1'b1;
        end else if ((grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_ready == 1'b1)) begin
            grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if (((targetBlock2_reg_209 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_ready == 1'b1)) begin
            grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start_reg <= 1'b0;
    end else begin
        if (((targetBlock3_reg_213 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
            grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start_reg <= 1'b1;
        end else if ((grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_ready == 1'b1)) begin
            grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                result_preg[0] <= 1'b0;
        result_preg[1] <= 1'b0;
    end else begin
        if (((targetBlock3_reg_213 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
                        result_preg[1 : 0] <= select_ln70_fu_168_p3[1 : 0];
        end else if (((targetBlock2_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                        result_preg[1 : 0] <= select_ln54_fu_150_p3[1 : 0];
        end else if (((targetBlock1_reg_205 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                        result_preg[1 : 0] <= select_ln38_fu_132_p3[1 : 0];
        end else if (((targetBlock_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                        result_preg[1 : 0] <= select_ln22_fu_114_p3[1 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_symbol_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        symbol_1_loc_fu_54 <= grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_symbol_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_symbol_2_out_ap_vld == 1'b1))) begin
        symbol_2_loc_fu_50 <= grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_symbol_2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_symbol_3_out_ap_vld == 1'b1))) begin
        symbol_3_loc_fu_46 <= grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_symbol_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_symbol_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        symbol_loc_fu_58 <= grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_symbol_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        targetBlock1_reg_205 <= grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        targetBlock2_reg_209 <= grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        targetBlock3_reg_213 <= grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        targetBlock_reg_201 <= grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_return;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state10_on_subcall_done)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((targetBlock3_reg_213 == 1'd1) & (targetBlock2_reg_209 == 1'd1) & (targetBlock1_reg_205 == 1'd1) & (targetBlock_reg_201 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        board_Addr_A = grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        board_Addr_A = grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        board_Addr_A = grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        board_Addr_A = grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        board_Addr_A = grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_Addr_A;
    end else begin
        board_Addr_A = 'bx;
    end
end

always @ (*) begin
    if (((targetBlock3_reg_213 == 1'd1) & (targetBlock2_reg_209 == 1'd1) & (targetBlock1_reg_205 == 1'd1) & (targetBlock_reg_201 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        board_EN_A = grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        board_EN_A = grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        board_EN_A = grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        board_EN_A = grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        board_EN_A = grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_EN_A;
    end else begin
        board_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((targetBlock3_reg_213 == 1'd1) & (targetBlock2_reg_209 == 1'd1) & (targetBlock1_reg_205 == 1'd1) & (targetBlock_reg_201 == 1'd1) & (1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10) & (grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_return == 1'd1))) begin
        result = 32'd3;
    end else if (((targetBlock3_reg_213 == 1'd1) & (targetBlock2_reg_209 == 1'd1) & (targetBlock1_reg_205 == 1'd1) & (targetBlock_reg_201 == 1'd1) & (1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10) & (grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_return == 1'd0))) begin
        result = 32'd0;
    end else if (((targetBlock3_reg_213 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        result = select_ln70_fu_168_p3;
    end else if (((targetBlock2_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        result = select_ln54_fu_150_p3;
    end else if (((targetBlock1_reg_205 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        result = select_ln38_fu_132_p3;
    end else if (((targetBlock_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        result = select_ln22_fu_114_p3;
    end else begin
        result = result_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((targetBlock_reg_201 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((targetBlock1_reg_205 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((targetBlock2_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10_on_subcall_done = ((ap_predicate_op54_call_state10 == 1'b1) & (grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_done == 1'b0));
end

always @ (*) begin
    ap_predicate_op54_call_state10 = ((targetBlock3_reg_213 == 1'd1) & (targetBlock2_reg_209 == 1'd1) & (targetBlock1_reg_205 == 1'd1) & (targetBlock_reg_201 == 1'd1));
end

assign board_Clk_A = ap_clk;

assign board_Din_A = 8'd0;

assign board_Rst_A = ap_rst;

assign board_WEN_A = 1'd0;

assign grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start = grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start_reg;

assign grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start = grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start_reg;

assign grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start = grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start_reg;

assign grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start = grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start_reg;

assign grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start = grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start_reg;

assign icmp_ln22_fu_108_p2 = ((symbol_loc_fu_58 == 8'd88) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_126_p2 = ((symbol_1_loc_fu_54 == 8'd88) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_144_p2 = ((symbol_2_loc_fu_50 == 8'd88) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_162_p2 = ((symbol_3_loc_fu_46 == 8'd88) ? 1'b1 : 1'b0);

assign select_ln22_fu_114_p3 = ((icmp_ln22_fu_108_p2[0:0] == 1'b1) ? 32'd1 : 32'd2);

assign select_ln38_fu_132_p3 = ((icmp_ln38_fu_126_p2[0:0] == 1'b1) ? 32'd1 : 32'd2);

assign select_ln54_fu_150_p3 = ((icmp_ln54_fu_144_p2[0:0] == 1'b1) ? 32'd1 : 32'd2);

assign select_ln70_fu_168_p3 = ((icmp_ln70_fu_162_p2[0:0] == 1'b1) ? 32'd1 : 32'd2);

always @ (posedge ap_clk) begin
    result_preg[31:2] <= 30'b000000000000000000000000000000;
end

endmodule //winning
