// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module winning_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        board_Addr_A,
        board_EN_A,
        board_WEN_A,
        board_Din_A,
        board_Dout_A,
        symbol_1_out,
        symbol_1_out_ap_vld,
        ap_return
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] board_Addr_A;
output   board_EN_A;
output  [0:0] board_WEN_A;
output  [7:0] board_Din_A;
input  [7:0] board_Dout_A;
output  [7:0] symbol_1_out;
output   symbol_1_out_ap_vld;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg board_EN_A;
reg symbol_1_out_ap_vld;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] reg_134;
wire    ap_CS_fsm_state8;
reg   [0:0] icmp_ln29_reg_331;
reg   [0:0] icmp_ln34_reg_402;
wire    ap_CS_fsm_state11;
reg   [0:0] icmp_ln35_reg_421;
wire    ap_CS_fsm_state14;
reg   [0:0] icmp_ln36_reg_435;
wire   [0:0] icmp_ln29_fu_161_p2;
wire    ap_CS_fsm_state2;
wire   [4:0] add_ln29_fu_167_p2;
reg   [4:0] add_ln29_reg_335;
reg   [2:0] col_load_reg_340;
wire   [0:0] icmp_ln30_fu_179_p2;
reg   [0:0] icmp_ln30_reg_345;
wire   [1:0] select_ln29_fu_185_p3;
reg   [1:0] select_ln29_reg_350;
wire   [2:0] add_ln29_1_fu_193_p2;
reg   [2:0] add_ln29_1_reg_357;
wire   [2:0] select_ln29_1_fu_199_p3;
reg   [2:0] select_ln29_1_reg_362;
wire    ap_CS_fsm_state3;
wire   [5:0] zext_ln29_1_fu_204_p1;
reg   [5:0] zext_ln29_1_reg_368;
wire   [5:0] sub_ln31_fu_222_p2;
reg   [5:0] sub_ln31_reg_374;
wire   [4:0] trunc_ln31_fu_228_p1;
reg   [4:0] trunc_ln31_reg_380;
wire   [5:0] add_ln31_fu_232_p2;
reg   [5:0] add_ln31_reg_385;
wire    ap_CS_fsm_state4;
reg   [7:0] symbol_reg_395;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln34_fu_245_p2;
wire    ap_CS_fsm_state6;
wire   [1:0] add_ln35_fu_250_p2;
reg   [1:0] add_ln35_reg_406;
wire   [4:0] add_ln35_2_fu_260_p2;
reg   [4:0] add_ln35_2_reg_411;
wire    ap_CS_fsm_state7;
wire   [0:0] grp_fu_138_p2;
wire    ap_CS_fsm_state9;
wire   [5:0] add_ln36_1_fu_275_p2;
reg   [5:0] add_ln36_1_reg_425;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state12;
wire   [5:0] add_ln37_1_fu_289_p2;
reg   [5:0] add_ln37_1_reg_439;
wire    ap_CS_fsm_state13;
reg   [0:0] ap_phi_mux_UnifiedRetVal_phi_fu_126_p4;
reg   [0:0] UnifiedRetVal_reg_122;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state16;
wire  signed [63:0] sext_ln32_fu_238_p1;
wire   [63:0] zext_ln35_fu_266_p1;
wire   [63:0] zext_ln36_fu_280_p1;
wire   [63:0] zext_ln37_fu_294_p1;
reg   [1:0] row_fu_66;
wire    ap_CS_fsm_state15;
reg   [2:0] col_fu_70;
reg   [4:0] indvar_flatten6_fu_74;
reg   [31:0] board_Addr_A_orig;
wire   [4:0] shl_ln_fu_211_p3;
wire   [5:0] zext_ln31_fu_218_p1;
wire   [5:0] row_2_cast12_fu_208_p1;
wire   [4:0] add_ln35_1_fu_255_p2;
wire   [4:0] zext_ln29_fu_242_p1;
wire   [5:0] add_ln36_fu_270_p2;
wire   [5:0] add_ln37_fu_284_p2;
reg   [0:0] ap_return_preg;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 ap_return_preg = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_126_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        UnifiedRetVal_reg_122 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        UnifiedRetVal_reg_122 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        col_fu_70 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state15) & (((((icmp_ln29_reg_331 == 1'd0) & (grp_fu_138_p2 == 1'd0)) | ((icmp_ln36_reg_435 == 1'd0) & (icmp_ln29_reg_331 == 1'd0))) | ((icmp_ln35_reg_421 == 1'd0) & (icmp_ln29_reg_331 == 1'd0))) | ((icmp_ln34_reg_402 == 1'd1) & (icmp_ln29_reg_331 == 1'd0))))) begin
        col_fu_70 <= select_ln29_1_reg_362;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten6_fu_74 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state15) & (((((icmp_ln29_reg_331 == 1'd0) & (grp_fu_138_p2 == 1'd0)) | ((icmp_ln36_reg_435 == 1'd0) & (icmp_ln29_reg_331 == 1'd0))) | ((icmp_ln35_reg_421 == 1'd0) & (icmp_ln29_reg_331 == 1'd0))) | ((icmp_ln34_reg_402 == 1'd1) & (icmp_ln29_reg_331 == 1'd0))))) begin
        indvar_flatten6_fu_74 <= add_ln29_reg_335;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        row_fu_66 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state15) & (((((icmp_ln29_reg_331 == 1'd0) & (grp_fu_138_p2 == 1'd0)) | ((icmp_ln36_reg_435 == 1'd0) & (icmp_ln29_reg_331 == 1'd0))) | ((icmp_ln35_reg_421 == 1'd0) & (icmp_ln29_reg_331 == 1'd0))) | ((icmp_ln34_reg_402 == 1'd1) & (icmp_ln29_reg_331 == 1'd0))))) begin
        row_fu_66 <= add_ln35_reg_406;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln29_fu_161_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln29_1_reg_357 <= add_ln29_1_fu_193_p2;
        col_load_reg_340 <= col_fu_70;
        icmp_ln30_reg_345 <= icmp_ln30_fu_179_p2;
        select_ln29_reg_350 <= select_ln29_fu_185_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln29_reg_335 <= add_ln29_fu_167_p2;
        icmp_ln29_reg_331 <= icmp_ln29_fu_161_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        add_ln31_reg_385 <= add_ln31_fu_232_p2;
        select_ln29_1_reg_362 <= select_ln29_1_fu_199_p3;
        sub_ln31_reg_374 <= sub_ln31_fu_222_p2;
        trunc_ln31_reg_380 <= trunc_ln31_fu_228_p1;
        zext_ln29_1_reg_368[2 : 0] <= zext_ln29_1_fu_204_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln34_fu_245_p2 == 1'd0))) begin
        add_ln35_2_reg_411 <= add_ln35_2_fu_260_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        add_ln35_reg_406 <= add_ln35_fu_250_p2;
        icmp_ln34_reg_402 <= icmp_ln34_fu_245_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_402 == 1'd0) & (icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (grp_fu_138_p2 == 1'd1))) begin
        add_ln36_1_reg_425 <= add_ln36_1_fu_275_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln35_reg_421 == 1'd1) & (icmp_ln34_reg_402 == 1'd0) & (icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state12) & (grp_fu_138_p2 == 1'd1))) begin
        add_ln37_1_reg_439 <= add_ln37_1_fu_289_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_reg_402 == 1'd0) & (icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        icmp_ln35_reg_421 <= grp_fu_138_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln35_reg_421 == 1'd1) & (icmp_ln34_reg_402 == 1'd0) & (icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        icmp_ln36_reg_435 <= grp_fu_138_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln36_reg_435 == 1'd1) & (icmp_ln35_reg_421 == 1'd1) & (icmp_ln34_reg_402 == 1'd0) & (icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state14)) | ((icmp_ln35_reg_421 == 1'd1) & (icmp_ln34_reg_402 == 1'd0) & (icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state11)) | ((icmp_ln34_reg_402 == 1'd0) & (icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        reg_134 <= board_Dout_A;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        symbol_reg_395 <= board_Dout_A;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_phi_mux_UnifiedRetVal_phi_fu_126_p4 = 1'd0;
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_126_p4 = UnifiedRetVal_reg_122;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_126_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        board_Addr_A_orig = zext_ln37_fu_294_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        board_Addr_A_orig = zext_ln36_fu_280_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        board_Addr_A_orig = zext_ln35_fu_266_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        board_Addr_A_orig = sext_ln32_fu_238_p1;
    end else begin
        board_Addr_A_orig = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4))) begin
        board_EN_A = 1'b1;
    end else begin
        board_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln29_reg_331 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        symbol_1_out_ap_vld = 1'b1;
    end else begin
        symbol_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (((((icmp_ln29_reg_331 == 1'd0) & (grp_fu_138_p2 == 1'd0)) | ((icmp_ln36_reg_435 == 1'd0) & (icmp_ln29_reg_331 == 1'd0))) | ((icmp_ln35_reg_421 == 1'd0) & (icmp_ln29_reg_331 == 1'd0))) | ((icmp_ln34_reg_402 == 1'd1) & (icmp_ln29_reg_331 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((icmp_ln29_reg_331 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln29_1_fu_193_p2 = (col_fu_70 + 3'd1);

assign add_ln29_fu_167_p2 = (indvar_flatten6_fu_74 + 5'd1);

assign add_ln31_fu_232_p2 = (sub_ln31_fu_222_p2 + zext_ln29_1_fu_204_p1);

assign add_ln35_1_fu_255_p2 = (trunc_ln31_reg_380 + 5'd7);

assign add_ln35_2_fu_260_p2 = (add_ln35_1_fu_255_p2 + zext_ln29_fu_242_p1);

assign add_ln35_fu_250_p2 = (select_ln29_reg_350 + 2'd1);

assign add_ln36_1_fu_275_p2 = (add_ln36_fu_270_p2 + zext_ln29_1_reg_368);

assign add_ln36_fu_270_p2 = (sub_ln31_reg_374 + 6'd14);

assign add_ln37_1_fu_289_p2 = (add_ln37_fu_284_p2 + zext_ln29_1_reg_368);

assign add_ln37_fu_284_p2 = (sub_ln31_reg_374 + 6'd21);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign board_Addr_A = board_Addr_A_orig << 32'd0;

assign board_Din_A = 8'd0;

assign board_WEN_A = 1'd0;

assign grp_fu_138_p2 = ((symbol_reg_395 == reg_134) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_161_p2 = ((indvar_flatten6_fu_74 == 5'd21) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_179_p2 = ((row_fu_66 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln34_fu_245_p2 = ((symbol_reg_395 == 8'd32) ? 1'b1 : 1'b0);

assign row_2_cast12_fu_208_p1 = select_ln29_reg_350;

assign select_ln29_1_fu_199_p3 = ((icmp_ln30_reg_345[0:0] == 1'b1) ? add_ln29_1_reg_357 : col_load_reg_340);

assign select_ln29_fu_185_p3 = ((icmp_ln30_fu_179_p2[0:0] == 1'b1) ? 2'd0 : row_fu_66);

assign sext_ln32_fu_238_p1 = $signed(add_ln31_reg_385);

assign shl_ln_fu_211_p3 = {{select_ln29_reg_350}, {3'd0}};

assign sub_ln31_fu_222_p2 = (zext_ln31_fu_218_p1 - row_2_cast12_fu_208_p1);

assign symbol_1_out = symbol_reg_395;

assign trunc_ln31_fu_228_p1 = sub_ln31_fu_222_p2[4:0];

assign zext_ln29_1_fu_204_p1 = select_ln29_1_fu_199_p3;

assign zext_ln29_fu_242_p1 = select_ln29_1_reg_362;

assign zext_ln31_fu_218_p1 = shl_ln_fu_211_p3;

assign zext_ln35_fu_266_p1 = add_ln35_2_reg_411;

assign zext_ln36_fu_280_p1 = add_ln36_1_reg_425;

assign zext_ln37_fu_294_p1 = add_ln37_1_reg_439;

always @ (posedge ap_clk) begin
    zext_ln29_1_reg_368[5:3] <= 3'b000;
end

endmodule //winning_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4
