// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module winning_winning_Pipeline_VITIS_LOOP_77_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        board_Addr_A,
        board_EN_A,
        board_WEN_A,
        board_Din_A,
        board_Dout_A,
        ap_return
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] board_Addr_A;
output   board_EN_A;
output  [0:0] board_WEN_A;
output  [7:0] board_Din_A;
input  [7:0] board_Dout_A;
output  [0:0] ap_return;

reg ap_idle;
reg board_EN_A;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state3;
wire    ap_block_state3_pp0_stage2_iter0;
wire   [0:0] icmp_ln78_fu_96_p2;
reg   [0:0] icmp_ln77_reg_112;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] merge_reg_59;
wire   [0:0] icmp_ln77_fu_79_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [5:0] add_ln77_fu_85_p2;
reg   [5:0] add_ln77_reg_116;
reg   [7:0] board_load_reg_126;
wire    ap_CS_fsm_state2;
wire    ap_block_state2_pp0_stage1_iter0;
reg   [0:0] ap_phi_mux_merge_phi_fu_63_p4;
wire   [63:0] i_cast_fu_91_p1;
reg   [5:0] i_fu_42;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_1;
wire   [31:0] board_Addr_A_orig;
reg   [0:0] ap_return_preg;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_return_preg = 1'd0;
#0 ap_done_reg = 1'b0;
end

winning_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln77_reg_112 == 1'd1) | (icmp_ln78_fu_96_p2 == 1'd1)))) begin
            ap_return_preg <= ap_phi_mux_merge_phi_fu_63_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        i_fu_42 <= 6'd0;
    end else if (((icmp_ln77_reg_112 == 1'd0) & (icmp_ln78_fu_96_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_fu_42 <= add_ln77_reg_116;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln77_reg_112 == 1'd0) & (icmp_ln78_fu_96_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        merge_reg_59 <= 1'd0;
    end else if (((icmp_ln77_fu_79_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        merge_reg_59 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        add_ln77_reg_116 <= add_ln77_fu_85_p2;
        icmp_ln77_reg_112 <= icmp_ln77_fu_79_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln77_reg_112 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        board_load_reg_126 <= board_Dout_A;
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln77_reg_112 == 1'd1) | (icmp_ln78_fu_96_p2 == 1'd1)))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_reg_112 == 1'd0) & (icmp_ln78_fu_96_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_phi_mux_merge_phi_fu_63_p4 = 1'd0;
    end else begin
        ap_phi_mux_merge_phi_fu_63_p4 = merge_reg_59;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln77_reg_112 == 1'd1) | (icmp_ln78_fu_96_p2 == 1'd1)))) begin
        ap_return = ap_phi_mux_merge_phi_fu_63_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_42;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        board_EN_A = 1'b1;
    end else begin
        board_EN_A = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln77_fu_85_p2 = (ap_sig_allocacmp_i_1 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign board_Addr_A = board_Addr_A_orig << 32'd0;

assign board_Addr_A_orig = i_cast_fu_91_p1;

assign board_Din_A = 8'd0;

assign board_WEN_A = 1'd0;

assign i_cast_fu_91_p1 = ap_sig_allocacmp_i_1;

assign icmp_ln77_fu_79_p2 = ((ap_sig_allocacmp_i_1 == 6'd42) ? 1'b1 : 1'b0);

assign icmp_ln78_fu_96_p2 = ((board_load_reg_126 == 8'd32) ? 1'b1 : 1'b0);

endmodule //winning_winning_Pipeline_VITIS_LOOP_77_9
