// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module winning_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        board_Addr_A,
        board_EN_A,
        board_WEN_A,
        board_Din_A,
        board_Dout_A,
        symbol_out,
        symbol_out_ap_vld,
        ap_return
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] board_Addr_A;
output   board_EN_A;
output  [0:0] board_WEN_A;
output  [7:0] board_Din_A;
input  [7:0] board_Dout_A;
output  [7:0] symbol_out;
output   symbol_out_ap_vld;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg board_EN_A;
reg symbol_out_ap_vld;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] reg_130;
wire    ap_CS_fsm_state8;
reg   [0:0] icmp_ln13_reg_333;
reg   [0:0] icmp_ln18_reg_391;
wire    ap_CS_fsm_state11;
reg   [0:0] icmp_ln19_reg_405;
wire    ap_CS_fsm_state14;
reg   [0:0] icmp_ln20_reg_419;
reg   [2:0] row_2_reg_323;
wire    ap_CS_fsm_state2;
wire   [5:0] empty_fu_172_p2;
reg   [5:0] empty_reg_328;
wire   [0:0] icmp_ln13_fu_178_p2;
wire   [4:0] add_ln13_fu_184_p2;
reg   [4:0] add_ln13_reg_337;
reg   [2:0] col_load_reg_342;
wire   [0:0] icmp_ln14_fu_193_p2;
reg   [0:0] icmp_ln14_reg_347;
wire   [2:0] add_ln13_1_fu_199_p2;
reg   [2:0] add_ln13_1_reg_354;
wire   [2:0] select_ln13_fu_205_p3;
reg   [2:0] select_ln13_reg_361;
wire    ap_CS_fsm_state3;
wire   [5:0] add_ln15_fu_237_p2;
reg   [5:0] add_ln15_reg_366;
wire    ap_CS_fsm_state4;
reg   [7:0] symbol_reg_379;
wire    ap_CS_fsm_state5;
wire   [2:0] select_ln13_2_fu_247_p3;
reg   [2:0] select_ln13_2_reg_386;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln18_fu_252_p2;
wire   [5:0] add_ln19_fu_257_p2;
reg   [5:0] add_ln19_reg_395;
wire    ap_CS_fsm_state7;
wire   [0:0] grp_fu_134_p2;
wire    ap_CS_fsm_state9;
wire   [5:0] add_ln20_fu_266_p2;
reg   [5:0] add_ln20_reg_409;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state12;
wire   [5:0] add_ln21_fu_275_p2;
reg   [5:0] add_ln21_reg_423;
wire    ap_CS_fsm_state13;
reg   [0:0] ap_phi_mux_UnifiedRetVal_phi_fu_122_p4;
reg   [0:0] UnifiedRetVal_reg_118;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state16;
wire   [63:0] zext_ln16_fu_243_p1;
wire   [63:0] zext_ln19_fu_262_p1;
wire   [63:0] zext_ln20_fu_271_p1;
wire   [63:0] zext_ln21_fu_280_p1;
reg   [2:0] col_fu_62;
wire   [2:0] add_ln14_fu_284_p2;
wire    ap_CS_fsm_state15;
reg   [2:0] row_fu_66;
reg   [4:0] indvar_flatten_fu_70;
reg   [31:0] board_Addr_A_orig;
wire   [5:0] p_shl_fu_164_p3;
wire   [5:0] zext_ln13_fu_160_p1;
wire   [5:0] p_shl_mid1_fu_214_p3;
wire   [5:0] zext_ln13_1_fu_211_p1;
wire   [5:0] p_mid1_fu_221_p2;
wire   [5:0] col_1_cast_fu_233_p1;
wire   [5:0] select_ln13_1_fu_227_p3;
reg   [0:0] ap_return_preg;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 ap_return_preg = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_122_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        UnifiedRetVal_reg_118 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        UnifiedRetVal_reg_118 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        col_fu_62 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state15) & (((((icmp_ln13_reg_333 == 1'd0) & (grp_fu_134_p2 == 1'd0)) | ((icmp_ln20_reg_419 == 1'd0) & (icmp_ln13_reg_333 == 1'd0))) | ((icmp_ln19_reg_405 == 1'd0) & (icmp_ln13_reg_333 == 1'd0))) | ((icmp_ln18_reg_391 == 1'd1) & (icmp_ln13_reg_333 == 1'd0))))) begin
        col_fu_62 <= add_ln14_fu_284_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_70 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state15) & (((((icmp_ln13_reg_333 == 1'd0) & (grp_fu_134_p2 == 1'd0)) | ((icmp_ln20_reg_419 == 1'd0) & (icmp_ln13_reg_333 == 1'd0))) | ((icmp_ln19_reg_405 == 1'd0) & (icmp_ln13_reg_333 == 1'd0))) | ((icmp_ln18_reg_391 == 1'd1) & (icmp_ln13_reg_333 == 1'd0))))) begin
        indvar_flatten_fu_70 <= add_ln13_reg_337;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        row_fu_66 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state15) & (((((icmp_ln13_reg_333 == 1'd0) & (grp_fu_134_p2 == 1'd0)) | ((icmp_ln20_reg_419 == 1'd0) & (icmp_ln13_reg_333 == 1'd0))) | ((icmp_ln19_reg_405 == 1'd0) & (icmp_ln13_reg_333 == 1'd0))) | ((icmp_ln18_reg_391 == 1'd1) & (icmp_ln13_reg_333 == 1'd0))))) begin
        row_fu_66 <= select_ln13_2_reg_386;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_fu_178_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln13_1_reg_354 <= add_ln13_1_fu_199_p2;
        col_load_reg_342 <= col_fu_62;
        icmp_ln14_reg_347 <= icmp_ln14_fu_193_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln13_reg_337 <= add_ln13_fu_184_p2;
        empty_reg_328 <= empty_fu_172_p2;
        icmp_ln13_reg_333 <= icmp_ln13_fu_178_p2;
        row_2_reg_323 <= row_fu_66;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        add_ln15_reg_366 <= add_ln15_fu_237_p2;
        select_ln13_reg_361 <= select_ln13_fu_205_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln18_fu_252_p2 == 1'd0))) begin
        add_ln19_reg_395 <= add_ln19_fu_257_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_reg_391 == 1'd0) & (icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (grp_fu_134_p2 == 1'd1))) begin
        add_ln20_reg_409 <= add_ln20_fu_266_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln19_reg_405 == 1'd1) & (icmp_ln18_reg_391 == 1'd0) & (icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state12) & (grp_fu_134_p2 == 1'd1))) begin
        add_ln21_reg_423 <= add_ln21_fu_275_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        icmp_ln18_reg_391 <= icmp_ln18_fu_252_p2;
        select_ln13_2_reg_386 <= select_ln13_2_fu_247_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_reg_391 == 1'd0) & (icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        icmp_ln19_reg_405 <= grp_fu_134_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln19_reg_405 == 1'd1) & (icmp_ln18_reg_391 == 1'd0) & (icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        icmp_ln20_reg_419 <= grp_fu_134_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln20_reg_419 == 1'd1) & (icmp_ln19_reg_405 == 1'd1) & (icmp_ln18_reg_391 == 1'd0) & (icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state14)) | ((icmp_ln19_reg_405 == 1'd1) & (icmp_ln18_reg_391 == 1'd0) & (icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state11)) | ((icmp_ln18_reg_391 == 1'd0) & (icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        reg_130 <= board_Dout_A;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        symbol_reg_379 <= board_Dout_A;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_phi_mux_UnifiedRetVal_phi_fu_122_p4 = 1'd0;
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_122_p4 = UnifiedRetVal_reg_118;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_122_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        board_Addr_A_orig = zext_ln21_fu_280_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        board_Addr_A_orig = zext_ln20_fu_271_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        board_Addr_A_orig = zext_ln19_fu_262_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        board_Addr_A_orig = zext_ln16_fu_243_p1;
    end else begin
        board_Addr_A_orig = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4))) begin
        board_EN_A = 1'b1;
    end else begin
        board_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln13_reg_333 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        symbol_out_ap_vld = 1'b1;
    end else begin
        symbol_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (((((icmp_ln13_reg_333 == 1'd0) & (grp_fu_134_p2 == 1'd0)) | ((icmp_ln20_reg_419 == 1'd0) & (icmp_ln13_reg_333 == 1'd0))) | ((icmp_ln19_reg_405 == 1'd0) & (icmp_ln13_reg_333 == 1'd0))) | ((icmp_ln18_reg_391 == 1'd1) & (icmp_ln13_reg_333 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((icmp_ln13_reg_333 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_1_fu_199_p2 = (row_fu_66 + 3'd1);

assign add_ln13_fu_184_p2 = (indvar_flatten_fu_70 + 5'd1);

assign add_ln14_fu_284_p2 = (select_ln13_reg_361 + 3'd1);

assign add_ln15_fu_237_p2 = (col_1_cast_fu_233_p1 + select_ln13_1_fu_227_p3);

assign add_ln19_fu_257_p2 = (add_ln15_reg_366 + 6'd1);

assign add_ln20_fu_266_p2 = (add_ln15_reg_366 + 6'd2);

assign add_ln21_fu_275_p2 = (add_ln15_reg_366 + 6'd3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign board_Addr_A = board_Addr_A_orig << 32'd0;

assign board_Din_A = 8'd0;

assign board_WEN_A = 1'd0;

assign col_1_cast_fu_233_p1 = select_ln13_fu_205_p3;

assign empty_fu_172_p2 = (p_shl_fu_164_p3 - zext_ln13_fu_160_p1);

assign grp_fu_134_p2 = ((symbol_reg_379 == reg_130) ? 1'b1 : 1'b0);

assign icmp_ln13_fu_178_p2 = ((indvar_flatten_fu_70 == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln14_fu_193_p2 = ((col_fu_62 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_252_p2 = ((symbol_reg_379 == 8'd32) ? 1'b1 : 1'b0);

assign p_mid1_fu_221_p2 = (p_shl_mid1_fu_214_p3 - zext_ln13_1_fu_211_p1);

assign p_shl_fu_164_p3 = {{row_fu_66}, {3'd0}};

assign p_shl_mid1_fu_214_p3 = {{add_ln13_1_reg_354}, {3'd0}};

assign select_ln13_1_fu_227_p3 = ((icmp_ln14_reg_347[0:0] == 1'b1) ? p_mid1_fu_221_p2 : empty_reg_328);

assign select_ln13_2_fu_247_p3 = ((icmp_ln14_reg_347[0:0] == 1'b1) ? add_ln13_1_reg_354 : row_2_reg_323);

assign select_ln13_fu_205_p3 = ((icmp_ln14_reg_347[0:0] == 1'b1) ? 3'd0 : col_load_reg_342);

assign symbol_out = symbol_reg_379;

assign zext_ln13_1_fu_211_p1 = add_ln13_1_reg_354;

assign zext_ln13_fu_160_p1 = row_fu_66;

assign zext_ln16_fu_243_p1 = add_ln15_reg_366;

assign zext_ln19_fu_262_p1 = add_ln19_reg_395;

assign zext_ln20_fu_271_p1 = add_ln20_reg_409;

assign zext_ln21_fu_280_p1 = add_ln21_reg_423;

endmodule //winning_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2
