// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module winning_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        board_Addr_A,
        board_EN_A,
        board_WEN_A,
        board_Din_A,
        board_Dout_A,
        symbol_3_out,
        symbol_3_out_ap_vld,
        ap_return
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] board_Addr_A;
output   board_EN_A;
output  [0:0] board_WEN_A;
output  [7:0] board_Din_A;
input  [7:0] board_Dout_A;
output  [7:0] symbol_3_out;
output   symbol_3_out_ap_vld;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg board_EN_A;
reg symbol_3_out_ap_vld;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] reg_136;
wire    ap_CS_fsm_state8;
reg   [0:0] icmp_ln61_reg_382;
reg   [0:0] icmp_ln66_reg_455;
wire    ap_CS_fsm_state11;
reg   [0:0] icmp_ln67_reg_469;
wire    ap_CS_fsm_state14;
reg   [0:0] icmp_ln68_reg_483;
reg   [1:0] row_1_reg_372;
wire    ap_CS_fsm_state2;
wire   [5:0] empty_fu_182_p2;
reg   [5:0] empty_reg_377;
wire   [0:0] icmp_ln61_fu_188_p2;
wire   [3:0] add_ln61_fu_194_p2;
reg   [3:0] add_ln61_reg_386;
reg   [2:0] col_load_reg_391;
wire   [0:0] icmp_ln62_fu_203_p2;
reg   [0:0] icmp_ln62_reg_396;
wire   [1:0] indvars_iv_next6046_fu_209_p2;
reg   [1:0] indvars_iv_next6046_reg_403;
wire   [5:0] p_mid124_fu_231_p2;
reg   [5:0] p_mid124_reg_408;
wire   [2:0] select_ln61_fu_237_p3;
reg   [2:0] select_ln61_reg_413;
wire    ap_CS_fsm_state3;
wire   [5:0] select_ln61_1_fu_243_p3;
reg   [5:0] select_ln61_1_reg_420;
wire   [5:0] add_ln63_fu_252_p2;
reg   [5:0] add_ln63_reg_427;
wire    ap_CS_fsm_state4;
reg   [7:0] symbol_reg_437;
wire    ap_CS_fsm_state5;
wire   [1:0] select_ln61_2_fu_262_p3;
reg   [1:0] select_ln61_2_reg_444;
wire    ap_CS_fsm_state6;
wire   [4:0] col_3_cast17_fu_267_p1;
reg   [4:0] col_3_cast17_reg_449;
wire   [0:0] icmp_ln66_fu_273_p2;
wire   [5:0] add_ln67_1_fu_288_p2;
reg   [5:0] add_ln67_1_reg_459;
wire    ap_CS_fsm_state7;
wire   [0:0] grp_fu_140_p2;
wire    ap_CS_fsm_state9;
wire   [5:0] add_ln68_1_fu_306_p2;
reg   [5:0] add_ln68_1_reg_473;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state12;
wire   [5:0] add_ln69_1_fu_324_p2;
reg   [5:0] add_ln69_1_reg_487;
wire    ap_CS_fsm_state13;
reg   [0:0] ap_phi_mux_UnifiedRetVal_phi_fu_128_p4;
reg   [0:0] UnifiedRetVal_reg_124;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state16;
wire   [63:0] zext_ln64_fu_258_p1;
wire   [63:0] zext_ln67_1_fu_293_p1;
wire   [63:0] zext_ln68_1_fu_311_p1;
wire   [63:0] zext_ln69_1_fu_329_p1;
reg   [2:0] col_fu_68;
wire   [2:0] add_ln62_fu_333_p2;
wire    ap_CS_fsm_state15;
reg   [1:0] row_fu_72;
reg   [3:0] indvar_flatten26_fu_76;
reg   [31:0] board_Addr_A_orig;
wire   [4:0] p_shl3_fu_170_p3;
wire   [5:0] p_shl3_cast_fu_178_p1;
wire   [5:0] zext_ln61_fu_166_p1;
wire   [4:0] p_shl3_mid1_fu_219_p3;
wire   [5:0] p_shl3_cast_mid1_fu_227_p1;
wire   [5:0] zext_ln61_1_fu_215_p1;
wire   [5:0] col_3_cast14_fu_248_p1;
wire   [3:0] col_3_cast_fu_270_p1;
wire   [3:0] add_ln67_fu_278_p2;
wire   [5:0] zext_ln67_fu_284_p1;
wire   [4:0] add_ln68_fu_297_p2;
wire   [5:0] zext_ln68_fu_302_p1;
wire   [4:0] add_ln69_fu_315_p2;
wire   [5:0] zext_ln69_fu_320_p1;
reg   [0:0] ap_return_preg;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 ap_return_preg = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_128_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        UnifiedRetVal_reg_124 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        UnifiedRetVal_reg_124 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        col_fu_68 <= 3'd3;
    end else if (((1'b1 == ap_CS_fsm_state15) & (((((icmp_ln61_reg_382 == 1'd0) & (grp_fu_140_p2 == 1'd0)) | ((icmp_ln68_reg_483 == 1'd0) & (icmp_ln61_reg_382 == 1'd0))) | ((icmp_ln67_reg_469 == 1'd0) & (icmp_ln61_reg_382 == 1'd0))) | ((icmp_ln66_reg_455 == 1'd1) & (icmp_ln61_reg_382 == 1'd0))))) begin
        col_fu_68 <= add_ln62_fu_333_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten26_fu_76 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state15) & (((((icmp_ln61_reg_382 == 1'd0) & (grp_fu_140_p2 == 1'd0)) | ((icmp_ln68_reg_483 == 1'd0) & (icmp_ln61_reg_382 == 1'd0))) | ((icmp_ln67_reg_469 == 1'd0) & (icmp_ln61_reg_382 == 1'd0))) | ((icmp_ln66_reg_455 == 1'd1) & (icmp_ln61_reg_382 == 1'd0))))) begin
        indvar_flatten26_fu_76 <= add_ln61_reg_386;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        row_fu_72 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state15) & (((((icmp_ln61_reg_382 == 1'd0) & (grp_fu_140_p2 == 1'd0)) | ((icmp_ln68_reg_483 == 1'd0) & (icmp_ln61_reg_382 == 1'd0))) | ((icmp_ln67_reg_469 == 1'd0) & (icmp_ln61_reg_382 == 1'd0))) | ((icmp_ln66_reg_455 == 1'd1) & (icmp_ln61_reg_382 == 1'd0))))) begin
        row_fu_72 <= select_ln61_2_reg_444;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln61_reg_386 <= add_ln61_fu_194_p2;
        empty_reg_377 <= empty_fu_182_p2;
        icmp_ln61_reg_382 <= icmp_ln61_fu_188_p2;
        row_1_reg_372 <= row_fu_72;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        add_ln63_reg_427 <= add_ln63_fu_252_p2;
        select_ln61_1_reg_420 <= select_ln61_1_fu_243_p3;
        select_ln61_reg_413 <= select_ln61_fu_237_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln66_fu_273_p2 == 1'd0))) begin
        add_ln67_1_reg_459 <= add_ln67_1_fu_288_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln66_reg_455 == 1'd0) & (icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (grp_fu_140_p2 == 1'd1))) begin
        add_ln68_1_reg_473 <= add_ln68_1_fu_306_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln67_reg_469 == 1'd1) & (icmp_ln66_reg_455 == 1'd0) & (icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state12) & (grp_fu_140_p2 == 1'd1))) begin
        add_ln69_1_reg_487 <= add_ln69_1_fu_324_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        col_3_cast17_reg_449[2 : 0] <= col_3_cast17_fu_267_p1[2 : 0];
        icmp_ln66_reg_455 <= icmp_ln66_fu_273_p2;
        select_ln61_2_reg_444 <= select_ln61_2_fu_262_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        col_load_reg_391 <= col_fu_68;
        icmp_ln62_reg_396 <= icmp_ln62_fu_203_p2;
        indvars_iv_next6046_reg_403 <= indvars_iv_next6046_fu_209_p2;
        p_mid124_reg_408 <= p_mid124_fu_231_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln66_reg_455 == 1'd0) & (icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        icmp_ln67_reg_469 <= grp_fu_140_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln67_reg_469 == 1'd1) & (icmp_ln66_reg_455 == 1'd0) & (icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        icmp_ln68_reg_483 <= grp_fu_140_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln68_reg_483 == 1'd1) & (icmp_ln67_reg_469 == 1'd1) & (icmp_ln66_reg_455 == 1'd0) & (icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state14)) | ((icmp_ln67_reg_469 == 1'd1) & (icmp_ln66_reg_455 == 1'd0) & (icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state11)) | ((icmp_ln66_reg_455 == 1'd0) & (icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        reg_136 <= board_Dout_A;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        symbol_reg_437 <= board_Dout_A;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_phi_mux_UnifiedRetVal_phi_fu_128_p4 = 1'd0;
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_128_p4 = UnifiedRetVal_reg_124;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_128_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        board_Addr_A_orig = zext_ln69_1_fu_329_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        board_Addr_A_orig = zext_ln68_1_fu_311_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        board_Addr_A_orig = zext_ln67_1_fu_293_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        board_Addr_A_orig = zext_ln64_fu_258_p1;
    end else begin
        board_Addr_A_orig = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4))) begin
        board_EN_A = 1'b1;
    end else begin
        board_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln61_reg_382 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        symbol_3_out_ap_vld = 1'b1;
    end else begin
        symbol_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (((((icmp_ln61_reg_382 == 1'd0) & (grp_fu_140_p2 == 1'd0)) | ((icmp_ln68_reg_483 == 1'd0) & (icmp_ln61_reg_382 == 1'd0))) | ((icmp_ln67_reg_469 == 1'd0) & (icmp_ln61_reg_382 == 1'd0))) | ((icmp_ln66_reg_455 == 1'd1) & (icmp_ln61_reg_382 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((icmp_ln61_reg_382 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln61_fu_194_p2 = (indvar_flatten26_fu_76 + 4'd1);

assign add_ln62_fu_333_p2 = (select_ln61_reg_413 + 3'd1);

assign add_ln63_fu_252_p2 = (col_3_cast14_fu_248_p1 + select_ln61_1_fu_243_p3);

assign add_ln67_1_fu_288_p2 = (zext_ln67_fu_284_p1 + select_ln61_1_reg_420);

assign add_ln67_fu_278_p2 = (col_3_cast_fu_270_p1 + 4'd6);

assign add_ln68_1_fu_306_p2 = (zext_ln68_fu_302_p1 + select_ln61_1_reg_420);

assign add_ln68_fu_297_p2 = (col_3_cast17_reg_449 + 5'd12);

assign add_ln69_1_fu_324_p2 = (zext_ln69_fu_320_p1 + select_ln61_1_reg_420);

assign add_ln69_fu_315_p2 = ($signed(col_3_cast17_reg_449) + $signed(5'd18));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign board_Addr_A = board_Addr_A_orig << 32'd0;

assign board_Din_A = 8'd0;

assign board_WEN_A = 1'd0;

assign col_3_cast14_fu_248_p1 = select_ln61_fu_237_p3;

assign col_3_cast17_fu_267_p1 = select_ln61_reg_413;

assign col_3_cast_fu_270_p1 = select_ln61_reg_413;

assign empty_fu_182_p2 = (p_shl3_cast_fu_178_p1 - zext_ln61_fu_166_p1);

assign grp_fu_140_p2 = ((symbol_reg_437 == reg_136) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_188_p2 = ((indvar_flatten26_fu_76 == 4'd12) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_203_p2 = ((col_fu_68 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_273_p2 = ((symbol_reg_437 == 8'd32) ? 1'b1 : 1'b0);

assign indvars_iv_next6046_fu_209_p2 = (row_fu_72 + 2'd1);

assign p_mid124_fu_231_p2 = (p_shl3_cast_mid1_fu_227_p1 - zext_ln61_1_fu_215_p1);

assign p_shl3_cast_fu_178_p1 = p_shl3_fu_170_p3;

assign p_shl3_cast_mid1_fu_227_p1 = p_shl3_mid1_fu_219_p3;

assign p_shl3_fu_170_p3 = {{row_fu_72}, {3'd0}};

assign p_shl3_mid1_fu_219_p3 = {{indvars_iv_next6046_fu_209_p2}, {3'd0}};

assign select_ln61_1_fu_243_p3 = ((icmp_ln62_reg_396[0:0] == 1'b1) ? p_mid124_reg_408 : empty_reg_377);

assign select_ln61_2_fu_262_p3 = ((icmp_ln62_reg_396[0:0] == 1'b1) ? indvars_iv_next6046_reg_403 : row_1_reg_372);

assign select_ln61_fu_237_p3 = ((icmp_ln62_reg_396[0:0] == 1'b1) ? 3'd3 : col_load_reg_391);

assign symbol_3_out = symbol_reg_437;

assign zext_ln61_1_fu_215_p1 = indvars_iv_next6046_fu_209_p2;

assign zext_ln61_fu_166_p1 = row_fu_72;

assign zext_ln64_fu_258_p1 = add_ln63_reg_427;

assign zext_ln67_1_fu_293_p1 = add_ln67_1_reg_459;

assign zext_ln67_fu_284_p1 = add_ln67_fu_278_p2;

assign zext_ln68_1_fu_311_p1 = add_ln68_1_reg_473;

assign zext_ln68_fu_302_p1 = add_ln68_fu_297_p2;

assign zext_ln69_1_fu_329_p1 = add_ln69_1_reg_487;

assign zext_ln69_fu_320_p1 = add_ln69_fu_315_p2;

always @ (posedge ap_clk) begin
    col_3_cast17_reg_449[4:3] <= 2'b00;
end

endmodule //winning_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8
