-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity winning is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    board_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    board_EN_A : OUT STD_LOGIC;
    board_WEN_A : OUT STD_LOGIC_VECTOR (0 downto 0);
    board_Din_A : OUT STD_LOGIC_VECTOR (7 downto 0);
    board_Dout_A : IN STD_LOGIC_VECTOR (7 downto 0);
    board_Clk_A : OUT STD_LOGIC;
    board_Rst_A : OUT STD_LOGIC;
    result : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of winning is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "winning_winning,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=229,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=506,HLS_SYN_LUT=1742,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_58 : STD_LOGIC_VECTOR (7 downto 0) := "01011000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal targetBlock_reg_201 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal targetBlock1_reg_205 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal targetBlock2_reg_209 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal targetBlock3_reg_213 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_done : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_idle : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_ready : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_EN_A : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_WEN_A : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_Din_A : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_symbol_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_symbol_out_ap_vld : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_done : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_idle : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_ready : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_EN_A : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_WEN_A : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_Din_A : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_symbol_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_symbol_1_out_ap_vld : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_done : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_idle : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_ready : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_EN_A : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_WEN_A : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_Din_A : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_symbol_2_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_symbol_2_out_ap_vld : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_done : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_idle : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_ready : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_EN_A : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_WEN_A : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_Din_A : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_symbol_3_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_symbol_3_out_ap_vld : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_done : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_idle : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_ready : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_EN_A : STD_LOGIC;
    signal grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_WEN_A : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_Din_A : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start_reg : STD_LOGIC := '0';
    signal symbol_loc_fu_58 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal symbol_1_loc_fu_54 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal symbol_2_loc_fu_50 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal symbol_3_loc_fu_46 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal select_ln22_fu_114_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln38_fu_132_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln54_fu_150_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln70_fu_168_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_op54_call_state10 : BOOLEAN;
    signal ap_block_state10_on_subcall_done : BOOLEAN;
    signal icmp_ln22_fu_108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_fu_126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component winning_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        board_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        board_EN_A : OUT STD_LOGIC;
        board_WEN_A : OUT STD_LOGIC_VECTOR (0 downto 0);
        board_Din_A : OUT STD_LOGIC_VECTOR (7 downto 0);
        board_Dout_A : IN STD_LOGIC_VECTOR (7 downto 0);
        symbol_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        symbol_out_ap_vld : OUT STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component winning_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        board_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        board_EN_A : OUT STD_LOGIC;
        board_WEN_A : OUT STD_LOGIC_VECTOR (0 downto 0);
        board_Din_A : OUT STD_LOGIC_VECTOR (7 downto 0);
        board_Dout_A : IN STD_LOGIC_VECTOR (7 downto 0);
        symbol_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        symbol_1_out_ap_vld : OUT STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component winning_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        board_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        board_EN_A : OUT STD_LOGIC;
        board_WEN_A : OUT STD_LOGIC_VECTOR (0 downto 0);
        board_Din_A : OUT STD_LOGIC_VECTOR (7 downto 0);
        board_Dout_A : IN STD_LOGIC_VECTOR (7 downto 0);
        symbol_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        symbol_2_out_ap_vld : OUT STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component winning_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        board_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        board_EN_A : OUT STD_LOGIC;
        board_WEN_A : OUT STD_LOGIC_VECTOR (0 downto 0);
        board_Din_A : OUT STD_LOGIC_VECTOR (7 downto 0);
        board_Dout_A : IN STD_LOGIC_VECTOR (7 downto 0);
        symbol_3_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        symbol_3_out_ap_vld : OUT STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component winning_winning_Pipeline_VITIS_LOOP_77_9 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        board_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        board_EN_A : OUT STD_LOGIC;
        board_WEN_A : OUT STD_LOGIC_VECTOR (0 downto 0);
        board_Din_A : OUT STD_LOGIC_VECTOR (7 downto 0);
        board_Dout_A : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71 : component winning_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start,
        ap_done => grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_done,
        ap_idle => grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_idle,
        ap_ready => grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_ready,
        board_Addr_A => grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_Addr_A,
        board_EN_A => grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_EN_A,
        board_WEN_A => grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_WEN_A,
        board_Din_A => grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_Din_A,
        board_Dout_A => board_Dout_A,
        symbol_out => grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_symbol_out,
        symbol_out_ap_vld => grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_symbol_out_ap_vld,
        ap_return => grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_return);

    grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78 : component winning_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start,
        ap_done => grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_done,
        ap_idle => grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_idle,
        ap_ready => grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_ready,
        board_Addr_A => grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_Addr_A,
        board_EN_A => grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_EN_A,
        board_WEN_A => grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_WEN_A,
        board_Din_A => grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_Din_A,
        board_Dout_A => board_Dout_A,
        symbol_1_out => grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_symbol_1_out,
        symbol_1_out_ap_vld => grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_symbol_1_out_ap_vld,
        ap_return => grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_return);

    grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85 : component winning_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start,
        ap_done => grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_done,
        ap_idle => grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_idle,
        ap_ready => grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_ready,
        board_Addr_A => grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_Addr_A,
        board_EN_A => grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_EN_A,
        board_WEN_A => grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_WEN_A,
        board_Din_A => grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_Din_A,
        board_Dout_A => board_Dout_A,
        symbol_2_out => grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_symbol_2_out,
        symbol_2_out_ap_vld => grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_symbol_2_out_ap_vld,
        ap_return => grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_return);

    grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92 : component winning_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start,
        ap_done => grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_done,
        ap_idle => grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_idle,
        ap_ready => grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_ready,
        board_Addr_A => grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_Addr_A,
        board_EN_A => grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_EN_A,
        board_WEN_A => grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_WEN_A,
        board_Din_A => grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_Din_A,
        board_Dout_A => board_Dout_A,
        symbol_3_out => grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_symbol_3_out,
        symbol_3_out_ap_vld => grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_symbol_3_out_ap_vld,
        ap_return => grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_return);

    grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99 : component winning_winning_Pipeline_VITIS_LOOP_77_9
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start,
        ap_done => grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_done,
        ap_idle => grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_idle,
        ap_ready => grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_ready,
        board_Addr_A => grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_Addr_A,
        board_EN_A => grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_EN_A,
        board_WEN_A => grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_WEN_A,
        board_Din_A => grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_Din_A,
        board_Dout_A => board_Dout_A,
        ap_return => grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_ready = ap_const_logic_1)) then 
                    grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start_reg <= ap_const_logic_0;
            else
                if (((targetBlock_reg_201 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_ready = ap_const_logic_1)) then 
                    grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start_reg <= ap_const_logic_0;
            else
                if (((targetBlock1_reg_205 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_ready = ap_const_logic_1)) then 
                    grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start_reg <= ap_const_logic_0;
            else
                if (((targetBlock2_reg_209 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                    grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_ready = ap_const_logic_1)) then 
                    grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start_reg <= ap_const_logic_0;
            else
                if (((targetBlock3_reg_213 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                    grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_ready = ap_const_logic_1)) then 
                    grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    result_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                result_preg(0) <= '0';
                result_preg(1) <= '0';
            else
                if (((targetBlock3_reg_213 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                                        result_preg(1 downto 0) <= select_ln70_fu_168_p3(1 downto 0);
                elsif (((targetBlock2_reg_209 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                                        result_preg(1 downto 0) <= select_ln54_fu_150_p3(1 downto 0);
                elsif (((targetBlock1_reg_205 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                                        result_preg(1 downto 0) <= select_ln38_fu_132_p3(1 downto 0);
                elsif (((targetBlock_reg_201 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                                        result_preg(1 downto 0) <= select_ln22_fu_114_p3(1 downto 0);
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_symbol_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                symbol_1_loc_fu_54 <= grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_symbol_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_symbol_2_out_ap_vld = ap_const_logic_1))) then
                symbol_2_loc_fu_50 <= grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_symbol_2_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_symbol_3_out_ap_vld = ap_const_logic_1))) then
                symbol_3_loc_fu_46 <= grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_symbol_3_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_symbol_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                symbol_loc_fu_58 <= grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_symbol_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                targetBlock1_reg_205 <= grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                targetBlock2_reg_209 <= grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                targetBlock3_reg_213 <= grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                targetBlock_reg_201 <= grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_return;
            end if;
        end if;
    end process;
    result_preg(31 downto 2) <= "000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, targetBlock_reg_201, ap_CS_fsm_state2, targetBlock1_reg_205, ap_CS_fsm_state4, targetBlock2_reg_209, ap_CS_fsm_state6, ap_CS_fsm_state8, grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_done, grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_done, grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_done, grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state10, ap_block_state10_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((targetBlock_reg_201 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((targetBlock1_reg_205 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((targetBlock2_reg_209 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(ap_block_state10_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state10_on_subcall_done)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_done)
    begin
        if ((grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_done)
    begin
        if ((grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_done)
    begin
        if ((grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_done)
    begin
        if ((grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state10_on_subcall_done_assign_proc : process(grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_done, ap_predicate_op54_call_state10)
    begin
                ap_block_state10_on_subcall_done <= ((ap_predicate_op54_call_state10 = ap_const_boolean_1) and (grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state10, ap_block_state10_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op54_call_state10_assign_proc : process(targetBlock_reg_201, targetBlock1_reg_205, targetBlock2_reg_209, targetBlock3_reg_213)
    begin
                ap_predicate_op54_call_state10 <= ((targetBlock3_reg_213 = ap_const_lv1_1) and (targetBlock2_reg_209 = ap_const_lv1_1) and (targetBlock1_reg_205 = ap_const_lv1_1) and (targetBlock_reg_201 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state10, ap_block_state10_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    board_Addr_A_assign_proc : process(targetBlock_reg_201, ap_CS_fsm_state2, targetBlock1_reg_205, ap_CS_fsm_state4, targetBlock2_reg_209, ap_CS_fsm_state6, targetBlock3_reg_213, ap_CS_fsm_state8, grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_Addr_A, grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_Addr_A, grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_Addr_A, grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_Addr_A, grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_Addr_A, ap_CS_fsm_state10)
    begin
        if (((targetBlock3_reg_213 = ap_const_lv1_1) and (targetBlock2_reg_209 = ap_const_lv1_1) and (targetBlock1_reg_205 = ap_const_lv1_1) and (targetBlock_reg_201 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            board_Addr_A <= grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_Addr_A;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            board_Addr_A <= grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_Addr_A;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            board_Addr_A <= grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_Addr_A;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            board_Addr_A <= grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_Addr_A;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            board_Addr_A <= grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_Addr_A;
        else 
            board_Addr_A <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    board_Clk_A <= ap_clk;
    board_Din_A <= ap_const_lv8_0;

    board_EN_A_assign_proc : process(targetBlock_reg_201, ap_CS_fsm_state2, targetBlock1_reg_205, ap_CS_fsm_state4, targetBlock2_reg_209, ap_CS_fsm_state6, targetBlock3_reg_213, ap_CS_fsm_state8, grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_EN_A, grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_EN_A, grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_EN_A, grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_EN_A, grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_EN_A, ap_CS_fsm_state10)
    begin
        if (((targetBlock3_reg_213 = ap_const_lv1_1) and (targetBlock2_reg_209 = ap_const_lv1_1) and (targetBlock1_reg_205 = ap_const_lv1_1) and (targetBlock_reg_201 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            board_EN_A <= grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_board_EN_A;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            board_EN_A <= grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_board_EN_A;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            board_EN_A <= grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_board_EN_A;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            board_EN_A <= grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_board_EN_A;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            board_EN_A <= grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_board_EN_A;
        else 
            board_EN_A <= ap_const_logic_0;
        end if; 
    end process;

    board_Rst_A <= ap_rst;
    board_WEN_A <= ap_const_lv1_0;
    grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start <= grp_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2_fu_71_ap_start_reg;
    grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start <= grp_winning_Pipeline_VITIS_LOOP_29_3_VITIS_LOOP_30_4_fu_78_ap_start_reg;
    grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start <= grp_winning_Pipeline_VITIS_LOOP_45_5_VITIS_LOOP_46_6_fu_85_ap_start_reg;
    grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start <= grp_winning_Pipeline_VITIS_LOOP_61_7_VITIS_LOOP_62_8_fu_92_ap_start_reg;
    grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start <= grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_start_reg;
    icmp_ln22_fu_108_p2 <= "1" when (symbol_loc_fu_58 = ap_const_lv8_58) else "0";
    icmp_ln38_fu_126_p2 <= "1" when (symbol_1_loc_fu_54 = ap_const_lv8_58) else "0";
    icmp_ln54_fu_144_p2 <= "1" when (symbol_2_loc_fu_50 = ap_const_lv8_58) else "0";
    icmp_ln70_fu_162_p2 <= "1" when (symbol_3_loc_fu_46 = ap_const_lv8_58) else "0";

    result_assign_proc : process(targetBlock_reg_201, targetBlock1_reg_205, targetBlock2_reg_209, targetBlock3_reg_213, grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_return, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state10, select_ln22_fu_114_p3, result_preg, select_ln38_fu_132_p3, select_ln54_fu_150_p3, select_ln70_fu_168_p3, ap_block_state10_on_subcall_done)
    begin
        if (((targetBlock3_reg_213 = ap_const_lv1_1) and (targetBlock2_reg_209 = ap_const_lv1_1) and (targetBlock1_reg_205 = ap_const_lv1_1) and (targetBlock_reg_201 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10) and (grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_return = ap_const_lv1_1))) then 
            result <= ap_const_lv32_3;
        elsif (((targetBlock3_reg_213 = ap_const_lv1_1) and (targetBlock2_reg_209 = ap_const_lv1_1) and (targetBlock1_reg_205 = ap_const_lv1_1) and (targetBlock_reg_201 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10) and (grp_winning_Pipeline_VITIS_LOOP_77_9_fu_99_ap_return = ap_const_lv1_0))) then 
            result <= ap_const_lv32_0;
        elsif (((targetBlock3_reg_213 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            result <= select_ln70_fu_168_p3;
        elsif (((targetBlock2_reg_209 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            result <= select_ln54_fu_150_p3;
        elsif (((targetBlock1_reg_205 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            result <= select_ln38_fu_132_p3;
        elsif (((targetBlock_reg_201 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            result <= select_ln22_fu_114_p3;
        else 
            result <= result_preg;
        end if; 
    end process;

    select_ln22_fu_114_p3 <= 
        ap_const_lv32_1 when (icmp_ln22_fu_108_p2(0) = '1') else 
        ap_const_lv32_2;
    select_ln38_fu_132_p3 <= 
        ap_const_lv32_1 when (icmp_ln38_fu_126_p2(0) = '1') else 
        ap_const_lv32_2;
    select_ln54_fu_150_p3 <= 
        ap_const_lv32_1 when (icmp_ln54_fu_144_p2(0) = '1') else 
        ap_const_lv32_2;
    select_ln70_fu_168_p3 <= 
        ap_const_lv32_1 when (icmp_ln70_fu_162_p2(0) = '1') else 
        ap_const_lv32_2;
end behav;
