-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity winning_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    board_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    board_EN_A : OUT STD_LOGIC;
    board_WEN_A : OUT STD_LOGIC_VECTOR (0 downto 0);
    board_Din_A : OUT STD_LOGIC_VECTOR (7 downto 0);
    board_Dout_A : IN STD_LOGIC_VECTOR (7 downto 0);
    symbol_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    symbol_out_ap_vld : OUT STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of winning_winning_Pipeline_VITIS_LOOP_13_1_VITIS_LOOP_14_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (16 downto 0) := "00000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (16 downto 0) := "00000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (16 downto 0) := "00000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (16 downto 0) := "00000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (16 downto 0) := "00000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (16 downto 0) := "00000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (16 downto 0) := "00001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (16 downto 0) := "00010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (16 downto 0) := "00100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (16 downto 0) := "01000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv8_20 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv6_3 : STD_LOGIC_VECTOR (5 downto 0) := "000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reg_130 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal icmp_ln13_reg_333 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_reg_391 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal icmp_ln19_reg_405 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal icmp_ln20_reg_419 : STD_LOGIC_VECTOR (0 downto 0);
    signal row_2_reg_323 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal empty_fu_172_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_reg_328 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln13_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln13_fu_184_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln13_reg_337 : STD_LOGIC_VECTOR (4 downto 0);
    signal col_load_reg_342 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln14_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_reg_347 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln13_1_fu_199_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln13_1_reg_354 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln13_fu_205_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln13_reg_361 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln15_fu_237_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln15_reg_366 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal symbol_reg_379 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal select_ln13_2_fu_247_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln13_2_reg_386 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln18_fu_252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln19_fu_257_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln19_reg_395 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal add_ln20_fu_266_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln20_reg_409 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal add_ln21_fu_275_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln21_reg_423 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_phi_mux_UnifiedRetVal_phi_fu_122_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal UnifiedRetVal_reg_118 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal zext_ln16_fu_243_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln19_fu_262_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_fu_271_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln21_fu_280_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal col_fu_62 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln14_fu_284_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal row_fu_66 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten_fu_70 : STD_LOGIC_VECTOR (4 downto 0);
    signal board_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal p_shl_fu_164_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln13_fu_160_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl_mid1_fu_214_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln13_1_fu_211_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_mid1_fu_221_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal col_1_cast_fu_233_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln13_1_fu_227_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv1_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                    ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_122_p4;
                end if; 
            end if;
        end if;
    end process;


    UnifiedRetVal_reg_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                UnifiedRetVal_reg_118 <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                UnifiedRetVal_reg_118 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    col_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                col_fu_62 <= ap_const_lv3_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state15) and (((((icmp_ln13_reg_333 = ap_const_lv1_0) and (grp_fu_134_p2 = ap_const_lv1_0)) or ((icmp_ln20_reg_419 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0))) or ((icmp_ln19_reg_405 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0))) or ((icmp_ln18_reg_391 = ap_const_lv1_1) and (icmp_ln13_reg_333 = ap_const_lv1_0))))) then 
                col_fu_62 <= add_ln14_fu_284_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_fu_70 <= ap_const_lv5_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state15) and (((((icmp_ln13_reg_333 = ap_const_lv1_0) and (grp_fu_134_p2 = ap_const_lv1_0)) or ((icmp_ln20_reg_419 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0))) or ((icmp_ln19_reg_405 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0))) or ((icmp_ln18_reg_391 = ap_const_lv1_1) and (icmp_ln13_reg_333 = ap_const_lv1_0))))) then 
                indvar_flatten_fu_70 <= add_ln13_reg_337;
            end if; 
        end if;
    end process;

    row_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                row_fu_66 <= ap_const_lv3_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state15) and (((((icmp_ln13_reg_333 = ap_const_lv1_0) and (grp_fu_134_p2 = ap_const_lv1_0)) or ((icmp_ln20_reg_419 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0))) or ((icmp_ln19_reg_405 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0))) or ((icmp_ln18_reg_391 = ap_const_lv1_1) and (icmp_ln13_reg_333 = ap_const_lv1_0))))) then 
                row_fu_66 <= select_ln13_2_reg_386;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln13_fu_178_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                add_ln13_1_reg_354 <= add_ln13_1_fu_199_p2;
                col_load_reg_342 <= col_fu_62;
                icmp_ln14_reg_347 <= icmp_ln14_fu_193_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln13_reg_337 <= add_ln13_fu_184_p2;
                empty_reg_328 <= empty_fu_172_p2;
                icmp_ln13_reg_333 <= icmp_ln13_fu_178_p2;
                row_2_reg_323 <= row_fu_66;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                add_ln15_reg_366 <= add_ln15_fu_237_p2;
                select_ln13_reg_361 <= select_ln13_fu_205_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln18_fu_252_p2 = ap_const_lv1_0))) then
                add_ln19_reg_395 <= add_ln19_fu_257_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln18_reg_391 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9) and (grp_fu_134_p2 = ap_const_lv1_1))) then
                add_ln20_reg_409 <= add_ln20_fu_266_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln19_reg_405 = ap_const_lv1_1) and (icmp_ln18_reg_391 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state12) and (grp_fu_134_p2 = ap_const_lv1_1))) then
                add_ln21_reg_423 <= add_ln21_fu_275_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                icmp_ln18_reg_391 <= icmp_ln18_fu_252_p2;
                select_ln13_2_reg_386 <= select_ln13_2_fu_247_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln18_reg_391 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                icmp_ln19_reg_405 <= grp_fu_134_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln19_reg_405 = ap_const_lv1_1) and (icmp_ln18_reg_391 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                icmp_ln20_reg_419 <= grp_fu_134_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln20_reg_419 = ap_const_lv1_1) and (icmp_ln19_reg_405 = ap_const_lv1_1) and (icmp_ln18_reg_391 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state14)) or ((icmp_ln19_reg_405 = ap_const_lv1_1) and (icmp_ln18_reg_391 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((icmp_ln18_reg_391 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8)))) then
                reg_130 <= board_Dout_A;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                symbol_reg_379 <= board_Dout_A;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln13_reg_333, icmp_ln18_reg_391, icmp_ln19_reg_405, icmp_ln20_reg_419, grp_fu_134_p2, ap_CS_fsm_state15)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state15) and (((((icmp_ln13_reg_333 = ap_const_lv1_0) and (grp_fu_134_p2 = ap_const_lv1_0)) or ((icmp_ln20_reg_419 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0))) or ((icmp_ln19_reg_405 = ap_const_lv1_0) and (icmp_ln13_reg_333 = ap_const_lv1_0))) or ((icmp_ln18_reg_391 = ap_const_lv1_1) and (icmp_ln13_reg_333 = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((icmp_ln13_reg_333 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln13_1_fu_199_p2 <= std_logic_vector(unsigned(row_fu_66) + unsigned(ap_const_lv3_1));
    add_ln13_fu_184_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_70) + unsigned(ap_const_lv5_1));
    add_ln14_fu_284_p2 <= std_logic_vector(unsigned(select_ln13_reg_361) + unsigned(ap_const_lv3_1));
    add_ln15_fu_237_p2 <= std_logic_vector(unsigned(col_1_cast_fu_233_p1) + unsigned(select_ln13_1_fu_227_p3));
    add_ln19_fu_257_p2 <= std_logic_vector(unsigned(add_ln15_reg_366) + unsigned(ap_const_lv6_1));
    add_ln20_fu_266_p2 <= std_logic_vector(unsigned(add_ln15_reg_366) + unsigned(ap_const_lv6_2));
    add_ln21_fu_275_p2 <= std_logic_vector(unsigned(add_ln15_reg_366) + unsigned(ap_const_lv6_3));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_UnifiedRetVal_phi_fu_122_p4_assign_proc : process(icmp_ln13_reg_333, UnifiedRetVal_reg_118, ap_CS_fsm_state16)
    begin
        if (((icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            ap_phi_mux_UnifiedRetVal_phi_fu_122_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_UnifiedRetVal_phi_fu_122_p4 <= UnifiedRetVal_reg_118;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_phi_mux_UnifiedRetVal_phi_fu_122_p4, ap_CS_fsm_state16, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            ap_return <= ap_phi_mux_UnifiedRetVal_phi_fu_122_p4;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    board_Addr_A <= std_logic_vector(shift_left(unsigned(board_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_0(31-1 downto 0)))));

    board_Addr_A_orig_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state7, ap_CS_fsm_state10, ap_CS_fsm_state13, zext_ln16_fu_243_p1, zext_ln19_fu_262_p1, zext_ln20_fu_271_p1, zext_ln21_fu_280_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            board_Addr_A_orig <= zext_ln21_fu_280_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            board_Addr_A_orig <= zext_ln20_fu_271_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            board_Addr_A_orig <= zext_ln19_fu_262_p1(32 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            board_Addr_A_orig <= zext_ln16_fu_243_p1(32 - 1 downto 0);
        else 
            board_Addr_A_orig <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    board_Din_A <= ap_const_lv8_0;

    board_EN_A_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state7, ap_CS_fsm_state10, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            board_EN_A <= ap_const_logic_1;
        else 
            board_EN_A <= ap_const_logic_0;
        end if; 
    end process;

    board_WEN_A <= ap_const_lv1_0;
    col_1_cast_fu_233_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln13_fu_205_p3),6));
    empty_fu_172_p2 <= std_logic_vector(unsigned(p_shl_fu_164_p3) - unsigned(zext_ln13_fu_160_p1));
    grp_fu_134_p2 <= "1" when (symbol_reg_379 = reg_130) else "0";
    icmp_ln13_fu_178_p2 <= "1" when (indvar_flatten_fu_70 = ap_const_lv5_18) else "0";
    icmp_ln14_fu_193_p2 <= "1" when (col_fu_62 = ap_const_lv3_4) else "0";
    icmp_ln18_fu_252_p2 <= "1" when (symbol_reg_379 = ap_const_lv8_20) else "0";
    p_mid1_fu_221_p2 <= std_logic_vector(unsigned(p_shl_mid1_fu_214_p3) - unsigned(zext_ln13_1_fu_211_p1));
    p_shl_fu_164_p3 <= (row_fu_66 & ap_const_lv3_0);
    p_shl_mid1_fu_214_p3 <= (add_ln13_1_reg_354 & ap_const_lv3_0);
    select_ln13_1_fu_227_p3 <= 
        p_mid1_fu_221_p2 when (icmp_ln14_reg_347(0) = '1') else 
        empty_reg_328;
    select_ln13_2_fu_247_p3 <= 
        add_ln13_1_reg_354 when (icmp_ln14_reg_347(0) = '1') else 
        row_2_reg_323;
    select_ln13_fu_205_p3 <= 
        ap_const_lv3_0 when (icmp_ln14_reg_347(0) = '1') else 
        col_load_reg_342;
    symbol_out <= symbol_reg_379;

    symbol_out_ap_vld_assign_proc : process(icmp_ln13_reg_333, ap_CS_fsm_state16)
    begin
        if (((icmp_ln13_reg_333 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            symbol_out_ap_vld <= ap_const_logic_1;
        else 
            symbol_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln13_1_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln13_1_reg_354),6));
    zext_ln13_fu_160_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(row_fu_66),6));
    zext_ln16_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln15_reg_366),64));
    zext_ln19_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln19_reg_395),64));
    zext_ln20_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_reg_409),64));
    zext_ln21_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln21_reg_423),64));
end behav;
